apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: conversao-temperatura
  name: conversao-temperatura
spec:
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - image: kress/conversao-temperatura:latest
        name: conversao-temperatura
        ports:
          - containerPort: 8080
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: conversao-temperatura
  name: conversao-temperatura
spec:
  ports:
  - name: 8080-30002
    port: 8080
    protocol: TCP
    nodePort: 30002
  selector:
    app: conversao-temperatura
  type: NodePort
